name: Deploy to VPS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      # - name: SSH
      #   uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.x'

      # - name: Install npm dependencies
      #   run: npm install

      - name: Write SSH Private Key
        # check this thread to understand why its needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      
      - name: Rsync Version & Node Version & NPM Version
        run: |
          rsync --version
          node -v
          npm -v
      
      - name: Private Key
        run: cat ~/.ssh/id_rsa

      # - name: SSH Deploy
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     REMOTE_HOST: ${{ secrets.SSH_HOST }}
      #     REMOTE_USER: ${{ secrets.SSH_USER }}
      #     # ARGS: "-rlgoDzvc -i --delete"
      #     SOURCE: "dist/"
      #     TARGET: ${{ secrets.WORK_DIR }}
      #     # EXCLUDE: "/dist/, /node_modules/"